### ISSUE TITLE
Shitty app make crash

### ISSUE THREAD

**Issue by RRethy** [jameswolfeoliver/Pigeon#5]
me crash

**Comment by RRethy** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10219109-259938372_28-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by jameswolfeoliver** [comment]
@RRethy Thank you for your feedback! As i'm sure you're aware, this project is currently in early alpha stages. I'll be sure to let you know when I have a stable version available for testing :)
